### ISSUE TITLE
3. 幽浮關修正

### ISSUE THREAD

**Issue by machipriest** [Min901128/HuaiSheng_Airport#3]
讓幽浮永遠出現在畫面中

- [x] 修正幽浮範圍

**Comment by wannaflyhigh** [comment]
@machipriest 背景圖調整

**Comment by wannaflyhigh** [comment]
fixed in [修正小遊戲怪物跑出畫面外
](https://github.com/Min901128/HuaiSheng_Airport/commit/240a7c6df68e5704532d6dc5783d5a65095327fc)
